package hu.mostoha.mobile.kmp.huki.util

object TestTags {
    const val MAIN_FAB_MY_LOCATION_BUTTON = "MAIN_FAB_MY_LOCATION_BUTTON"
    const val MAIN_FAB_GPX_CONTROL_BUTTON = "MAIN_FAB_GPX_CONTROL_BUTTON"
    const val MAIN_FAB_GPX_TOGGLE_LINE_BUTTON = "MAIN_FAB_GPX_TOGGLE_LINE_BUTTON"
    const val MAIN_FAB_GPX_OVERVIEW_BUTTON = "MAIN_FAB_GPX_OVERVIEW_BUTTON"
    const val MAIN_FAB_GPX_CLEAR_BUTTON = "MAIN_FAB_GPX_CLEAR_BUTTON"
    const val MAIN_SCALE_BAR = "MAIN_SCALE_BAR"
    const val MAIN_SEARCH_BAR = "MAIN_SEARCH_BAR"

    const val MENU_BACK_BUTTON = "MENU_BACK_BUTTON"
    const val MENU_SCREEN_ROOT = "MENU_SCREEN_ROOT"
    const val MENU_APP_ICON = "MENU_APP_ICON"
    const val MENU_VERSION = "MENU_VERSION"
    const val MENU_ROW_GPX_COLLECTION = "MENU_ROW_GPX_COLLECTION"
    const val MENU_ROW_EMAIL = "MENU_ROW_EMAIL"
    const val MENU_ROW_FACEBOOK = "MENU_ROW_FACEBOOK"
    const val MENU_ROW_GITHUB = "MENU_ROW_GITHUB"
    const val MENU_ROW_LOCATION_IQ = "MENU_ROW_LOCATION_IQ"

    const val GPX_COLLECTION_SCREEN_ROOT = "GPX_COLLECTION_SCREEN_ROOT"
    const val GPX_COLLECTION_BACK_BUTTON = "GPX_COLLECTION_BACK_BUTTON"
    const val GPX_COLLECTION_HELP_BUTTON = "GPX_COLLECTION_HELP_BUTTON"
    const val GPX_COLLECTION_LIST = "GPX_COLLECTION_LIST"
    const val GPX_COLLECTION_EMPTY_VIEW = "GPX_COLLECTION_EMPTY_VIEW"
    const val GPX_COLLECTION_ITEM = "GPX_COLLECTION_ITEM"
    const val GPX_COLLECTION_ITEM_OPTIONS_BUTTON = "GPX_COLLECTION_ITEM_OPTIONS_BUTTON"
    const val GPX_COLLECTION_ITEM_DELETE_BUTTON = "GPX_COLLECTION_ITEM_DELETE_BUTTON"
    const val GPX_COLLECTION_DELETE_DIALOG_CONFIRM_BUTTON = "GPX_COLLECTION_DELETE_DIALOG_CONFIRM_BUTTON"

    const val GPX_TUTORIAL_SCREEN_ROOT = "GPX_TUTORIAL_SCREEN_ROOT"
    const val GPX_TUTORIAL_BACK_BUTTON = "GPX_TUTORIAL_BACK_BUTTON"
    const val GPX_TUTORIAL_TERMS_BUTTON = "GPX_TUTORIAL_TERMS_BUTTON"

    const val LOCATION_IQ_SCREEN_ROOT = "LOCATION_IQ_SCREEN_ROOT"
    const val LOCATION_IQ_BACK_BUTTON = "LOCATION_IQ_BACK_BUTTON"
    const val LOCATION_IQ_VISIT_WEBSITE = "LOCATION_IQ_VISIT_WEBSITE"

    const val MAP_MAPBOX = "MAP_MAPBOX"
    const val GPX_DETAILS_TITLE = "GPX_DETAILS_TITLE"
    const val SEARCH_RESULT_ITEM = "SEARCH_RESULT_ITEM"

    const val DESTINATIONS_SECTION = "DESTINATIONS_SECTION"
    const val DESTINATIONS_SEE_ALL_BUTTON = "DESTINATIONS_SEE_ALL_BUTTON"
    const val DESTINATION_CARD = "DESTINATION_CARD"
    const val DESTINATION_EXPAND_BUTTON = "DESTINATION_EXPAND_BUTTON"
}
