package hu.mostoha.mobile.kmp.huki.util

object TestTags {
    const val MAIN_FAB_MY_LOCATION_BUTTON = "MAIN_FAB_MY_LOCATION_BUTTON"
    const val MAIN_SCALE_BAR = "MAIN_SCALE_BAR"

    const val SETTINGS_BACK_BUTTON = "SETTINGS_BACK_BUTTON"
    const val SETTINGS_SCREEN_ROOT = "SETTINGS_SCREEN_ROOT"
    const val SETTINGS_APP_ICON = "SETTINGS_APP_ICON"
    const val SETTINGS_VERSION = "SETTINGS_VERSION"
    const val SETTINGS_ROW_EMAIL = "SETTINGS_ROW_EMAIL"
    const val SETTINGS_ROW_FACEBOOK = "SETTINGS_ROW_FACEBOOK"
    const val SETTINGS_ROW_GITHUB = "SETTINGS_ROW_GITHUB"
    const val SETTINGS_ROW_LOCATION_IQ = "SETTINGS_ROW_LOCATION_IQ"

    const val MAP_MAPBOX = "MAP_MAPBOX"
    const val GPX_DETAILS_TITLE = "GPX_DETAILS_TITLE"
    const val SEARCH_RESULT_ITEM = "SEARCH_RESULT_ITEM"
}
