package hu.mostoha.mobile.kmp.huki.util

object TestTags {
    const val MAIN_FAB_MY_LOCATION_BUTTON = "MAIN_FAB_MY_LOCATION_BUTTON"
    const val MAIN_FAB_GPX_CONTROL_BUTTON = "MAIN_FAB_GPX_CONTROL_BUTTON"
    const val MAIN_FAB_GPX_TOGGLE_LINE_BUTTON = "MAIN_FAB_GPX_TOGGLE_LINE_BUTTON"
    const val MAIN_FAB_GPX_OVERVIEW_BUTTON = "MAIN_FAB_GPX_OVERVIEW_BUTTON"
    const val MAIN_FAB_GPX_CLEAR_BUTTON = "MAIN_FAB_GPX_CLEAR_BUTTON"
    const val MAIN_SCALE_BAR = "MAIN_SCALE_BAR"
    const val MAIN_SEARCH_BAR = "MAIN_SEARCH_BAR"

    const val SETTINGS_BACK_BUTTON = "SETTINGS_BACK_BUTTON"
    const val SETTINGS_SCREEN_ROOT = "SETTINGS_SCREEN_ROOT"
    const val SETTINGS_APP_ICON = "SETTINGS_APP_ICON"
    const val SETTINGS_VERSION = "SETTINGS_VERSION"
    const val SETTINGS_ROW_EMAIL = "SETTINGS_ROW_EMAIL"
    const val SETTINGS_ROW_FACEBOOK = "SETTINGS_ROW_FACEBOOK"
    const val SETTINGS_ROW_GITHUB = "SETTINGS_ROW_GITHUB"
    const val SETTINGS_ROW_LOCATION_IQ = "SETTINGS_ROW_LOCATION_IQ"

    const val LOCATION_IQ_SCREEN_ROOT = "LOCATION_IQ_SCREEN_ROOT"
    const val LOCATION_IQ_BACK_BUTTON = "LOCATION_IQ_BACK_BUTTON"
    const val LOCATION_IQ_VISIT_WEBSITE = "LOCATION_IQ_VISIT_WEBSITE"

    const val MAP_MAPBOX = "MAP_MAPBOX"
    const val GPX_DETAILS_TITLE = "GPX_DETAILS_TITLE"
    const val SEARCH_RESULT_ITEM = "SEARCH_RESULT_ITEM"

    const val DESTINATIONS_SECTION = "DESTINATIONS_SECTION"
    const val DESTINATIONS_SEE_ALL_BUTTON = "DESTINATIONS_SEE_ALL_BUTTON"
    const val DESTINATION_CARD = "DESTINATION_CARD"
    const val DESTINATION_EXPAND_BUTTON = "DESTINATION_EXPAND_BUTTON"
}
