name: "Checkout with secrets"
description: "Checkout the repository with secrets"
inputs:
  MAPBOX_ACCESS_TOKEN_XML_BASE64:
    description: "MapBox Access Token XML as Base64 string"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code with history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: "temurin"

    - name: Copy MapBox Access Token XML to res/values
      shell: bash
      run: echo "${{ inputs.MAPBOX_ACCESS_TOKEN_XML_BASE64 }}" | base64 --decode > composeApp/src/androidMain/res/values/mapbox_access_token.xml
